using BurcatProtocol.Annotations;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Linq;
using System.Net.WebSockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Reflection.Metadata;
using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Security.Claims;
using System.Security.Principal;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;

namespace BurcatProtocol
{
    /// <summary>
    /// Represents an object that can be exchanged through the Burcat Data Protocol.
    /// </summary>
    /// <remarks>
    /// Burcat objects model object-oriented instances in a language-neutral form:
    /// an object reference, a revision, construction values, and mutable fields.
    /// <see cref="Guid.Empty"/> identifies objects with no provider reference, and
    /// <see cref="Guid.AllBitsSet"/> is reserved by the protocol to represent a
    /// <see langword="null"/> object reference.
    /// </remarks>
    public interface IBurcatObject
    {
        /// <summary>
        /// Gets or sets the provider reference that identifies this object.
        /// </summary>
        /// <remarks>
        /// <see cref="Guid.Empty"/> means the object has no provider reference and
        /// should be transferred by construction data and fields. The all-bits-set
        /// GUID is reserved by the protocol to represent <see langword="null"/>.
        /// </remarks>
        /// <exception cref="InvalidOperationException">
        /// Thrown when an implementation does not allow the identifier to be set.
        /// </exception>
        Guid Identifier { get; set; }

        /// <summary>
        /// Gets or sets the revision that identifies this object's current state.
        /// </summary>
        /// <remarks>
        /// Providers use this value to determine whether a referenced object is
        /// up to date. <see cref="Guid.Empty"/> means there is no known state or
        /// that the state must be regenerated by the implementation.
        /// </remarks>
        /// <exception cref="InvalidOperationException">
        /// Thrown when an implementation does not allow the revision to be set.
        /// </exception>
        Guid Revision { get; set; }

        /// <summary>
        /// Gets the fields that must be applied after construction to reproduce this object.
        /// </summary>
        /// <remarks>
        /// Field values are normally requested when the receiver has no usable
        /// reference for this object.
        /// </remarks>
        /// <returns>
        /// The fields and additional state values to configure after object creation.
        /// </returns>
        BurcatField[] GetBurcatFields();

        /// <summary>
        /// Applies protocol fields to this object after construction.
        /// </summary>
        /// <remarks>
        /// This method is intended for object construction by
        /// <see cref="IInternalProvider.ConstructObject(Guid?, Type, Guid, Guid, IBurcatObject?[], BurcatField[])"/>.
        /// Implementations should not treat this as a local mutation and should
        /// not change <see cref="Revision"/> while applying these fields.
        /// </remarks>
        /// <param name="fields">The fields and additional state values to apply.</param>
        [NotBurcatInvokable]
        void SetBurcatFields(BurcatField[] fields);

        /// <summary>
        /// Gets the values required to construct this object instance.
        /// </summary>
        /// <remarks>
        /// Construction values are protocol objects so another provider can create
        /// an equivalent instance before applying <see cref="GetBurcatFields"/>.
        /// They are normally requested when the receiver has no usable reference
        /// for this object.
        /// </remarks>
        /// <returns>The protocol values passed to the object's constructor.</returns>
        IBurcatObject?[] GetBurcatConstructionValues();
    }

    /// <summary>
    /// Provides the common base implementation for referenced Burcat objects.
    /// </summary>
    /// <remarks>
    /// The base class supplies identity, revision tracking, comparison behavior,
    /// field extraction, field application, and construction value translation for
    /// <see cref="IBurcatObject"/> implementations.
    /// </remarks>
    public abstract class BurcatObject : IBurcatObject, IComparable<BurcatObject>
    {
        [NotBurcatInvokable]
        private readonly bool canChangeIdentity;
        [NotBurcatInvokable]
        private Guid identifier;
        [NotBurcatInvokable]
        private Guid revision;

        /// <inheritdoc/>
        public Guid Identifier { get => identifier; set { if (canChangeIdentity) identifier = value; else throw new InvalidOperationException(); } }

        /// <inheritdoc/>
        public Guid Revision { get { if (canChangeIdentity && revision == Guid.Empty) revision = GuidExtensions.GenerateRandom(); return revision; } set { if (canChangeIdentity) revision = value; else throw new InvalidOperationException(); } }

        /// <summary>
        /// Initializes a referenced Burcat object with a new sequential identifier and revision.
        /// </summary>
        protected BurcatObject() { identifier = revision = GuidExtensions.GenerateSequential(); canChangeIdentity = true; }

        /// <summary>
        /// Initializes a Burcat object with a fixed identifier.
        /// </summary>
        /// <param name="identifier">
        /// The object identifier. <see cref="Guid.Empty"/> creates an unreferenced
        /// object whose identity can be assigned during construction.
        /// </param>
        protected BurcatObject(Guid identifier) { this.identifier = this.revision = identifier; canChangeIdentity = identifier == Guid.Empty; }

        /// <inheritdoc/>
        public int CompareTo(BurcatObject? other) => BurcatComparer.Default.Compare(this, other);

        /// <summary>
        /// Determines whether this object is equal to another object by protocol identity.
        /// </summary>
        /// <param name="obj">The object to compare with this instance.</param>
        /// <returns><see langword="true"/> when the objects are equal; otherwise, <see langword="false"/>.</returns>
        public override bool Equals(object? obj)
        {
            if (obj is BurcatObject other) return BurcatComparer.Default.Equals(this, other);
            else return base.Equals(obj);
        }

        /// <summary>
        /// Gets the hash code for this object's protocol identifier.
        /// </summary>
        /// <returns>A hash code for this object.</returns>
        public override int GetHashCode() => BurcatComparer.Default.GetHashCode(this);


        /// <summary>
        /// Updates a backing field and marks the revision for regeneration when the value changes.
        /// </summary>
        /// <typeparam name="T">The field value type.</typeparam>
        /// <param name="field">The backing field to update.</param>
        /// <param name="value">The new value to assign.</param>
        /// <returns><see langword="true"/> when the field changed; otherwise, <see langword="false"/>.</returns>
        [NotBurcatInvokable]
        protected bool ReviseField<T>(ref T field, T value)
        {
            if (EqualityComparer<T>.Default.Equals(field, value)) return false;
            else
            {
                field = value;
                if (canChangeIdentity) revision = Guid.Empty;

                return true;
            }
        }

        /// <inheritdoc/>
        public virtual BurcatField[] GetBurcatFields()
        {
            BurcatCache.AddToCache(GetType());
            return BurcatCache.GetFields(this);
        }

        /// <inheritdoc/>
        public virtual void SetBurcatFields(BurcatField[] fields)
        {
            BurcatCache.AddToCache(GetType());
            foreach (BurcatField field in fields) BurcatCache.SetField(GetType(), this, field);
        }

        IBurcatObject?[] IBurcatObject.GetBurcatConstructionValues() => BurcatTranslator.ObjectsTranslate(GetBurcatConstructionValues());

        /// <summary>
        /// Gets the CLR values required to construct this object instance.
        /// </summary>
        /// <returns>The constructor values before protocol translation.</returns>
        public abstract object?[] GetBurcatConstructionValues();
    }
}
